// FastFWD V3.4 Top Level with Internal FE Modules
// FE is instantiated inside, not exposed at top level
//
// NOTE: Runtime files (pyc_*.v) should be included during compilation:
//   iverilog -I../../../runtime/verilog ...

module fastfwd_v3_4 (
  input clk,
  input rst,                    // Active-high reset (converted to rst_n for FE)
  
  // Input ports - 4 lanes only
  input lane0_pkt_in_vld,
  input lane1_pkt_in_vld,
  input lane2_pkt_in_vld,
  input lane3_pkt_in_vld,
  input [127:0] lane0_pkt_in_data,
  input [127:0] lane1_pkt_in_data,
  input [127:0] lane2_pkt_in_data,
  input [127:0] lane3_pkt_in_data,
  input [4:0] lane0_pkt_in_ctrl,
  input [4:0] lane1_pkt_in_ctrl,
  input [4:0] lane2_pkt_in_ctrl,
  input [4:0] lane3_pkt_in_ctrl,
  
  // Output ports - 4 lanes only
  output lane0_pkt_out_vld,
  output [127:0] lane0_pkt_out_data,
  output lane1_pkt_out_vld,
  output [127:0] lane1_pkt_out_data,
  output lane2_pkt_out_vld,
  output [127:0] lane2_pkt_out_data,
  output lane3_pkt_out_vld,
  output [127:0] lane3_pkt_out_data,
  
  // Backpressure only
  output pkt_in_bkpr
);

  // =========================================================================
  // Internal signals between core and FE modules
  // =========================================================================
  wire [3:0] fwd_pkt_data_vld;      // Core -> FE
  wire [127:0] fwd0_pkt_data;
  wire [127:0] fwd1_pkt_data;
  wire [127:0] fwd2_pkt_data;
  wire [127:0] fwd3_pkt_data;
  wire [1:0] fwd0_pkt_lat;
  wire [1:0] fwd1_pkt_lat;
  wire [1:0] fwd2_pkt_lat;
  wire [1:0] fwd3_pkt_lat;
  wire [3:0] fwd_pkt_dp_vld;        // Core -> FE
  wire [127:0] fwd0_pkt_dp_data;
  wire [127:0] fwd1_pkt_dp_data;
  wire [127:0] fwd2_pkt_dp_data;
  wire [127:0] fwd3_pkt_dp_data;
  
  wire [3:0] fwded_pkt_data_vld;    // FE -> Core
  wire [127:0] fwded0_pkt_data;
  wire [127:0] fwded1_pkt_data;
  wire [127:0] fwded2_pkt_data;
  wire [127:0] fwded3_pkt_data;

  // Reset conversion (rst is active-high, FE needs active-low rst_n)
  wire rst_n = ~rst;

  // =========================================================================
  // Core module (generated by pyCircuit)
  // =========================================================================
  fastfwd_v3_4_core u_core (
    .clk(clk),
    .rst(rst),
    
    // Lane inputs
    .lane0_pkt_in_vld(lane0_pkt_in_vld),
    .lane1_pkt_in_vld(lane1_pkt_in_vld),
    .lane2_pkt_in_vld(lane2_pkt_in_vld),
    .lane3_pkt_in_vld(lane3_pkt_in_vld),
    .lane0_pkt_in_data(lane0_pkt_in_data),
    .lane1_pkt_in_data(lane1_pkt_in_data),
    .lane2_pkt_in_data(lane2_pkt_in_data),
    .lane3_pkt_in_data(lane3_pkt_in_data),
    .lane0_pkt_in_ctrl(lane0_pkt_in_ctrl),
    .lane1_pkt_in_ctrl(lane1_pkt_in_ctrl),
    .lane2_pkt_in_ctrl(lane2_pkt_in_ctrl),
    .lane3_pkt_in_ctrl(lane3_pkt_in_ctrl),
    
    // FE feedback (from FE modules below)
    .fwded0_pkt_data_vld(fwded_pkt_data_vld[0]),
    .fwded1_pkt_data_vld(fwded_pkt_data_vld[1]),
    .fwded2_pkt_data_vld(fwded_pkt_data_vld[2]),
    .fwded3_pkt_data_vld(fwded_pkt_data_vld[3]),
    .fwded0_pkt_data(fwded0_pkt_data),
    .fwded1_pkt_data(fwded1_pkt_data),
    .fwded2_pkt_data(fwded2_pkt_data),
    .fwded3_pkt_data(fwded3_pkt_data),
    
    // Lane outputs
    .lane0_pkt_out_vld(lane0_pkt_out_vld),
    .lane0_pkt_out_data(lane0_pkt_out_data),
    .lane1_pkt_out_vld(lane1_pkt_out_vld),
    .lane1_pkt_out_data(lane1_pkt_out_data),
    .lane2_pkt_out_vld(lane2_pkt_out_vld),
    .lane2_pkt_out_data(lane2_pkt_out_data),
    .lane3_pkt_out_vld(lane3_pkt_out_vld),
    .lane3_pkt_out_data(lane3_pkt_out_data),
    
    // FE control outputs (to FE modules below)
    .fwd0_pkt_data_vld(fwd_pkt_data_vld[0]),
    .fwd0_pkt_data(fwd0_pkt_data),
    .fwd0_pkt_lat(fwd0_pkt_lat),
    .fwd0_pkt_dp_vld(fwd_pkt_dp_vld[0]),
    .fwd0_pkt_dp_data(fwd0_pkt_dp_data),
    .fwd1_pkt_data_vld(fwd_pkt_data_vld[1]),
    .fwd1_pkt_data(fwd1_pkt_data),
    .fwd1_pkt_lat(fwd1_pkt_lat),
    .fwd1_pkt_dp_vld(fwd_pkt_dp_vld[1]),
    .fwd1_pkt_dp_data(fwd1_pkt_dp_data),
    .fwd2_pkt_data_vld(fwd_pkt_data_vld[2]),
    .fwd2_pkt_data(fwd2_pkt_data),
    .fwd2_pkt_lat(fwd2_pkt_lat),
    .fwd2_pkt_dp_vld(fwd_pkt_dp_vld[2]),
    .fwd2_pkt_dp_data(fwd2_pkt_dp_data),
    .fwd3_pkt_data_vld(fwd_pkt_data_vld[3]),
    .fwd3_pkt_data(fwd3_pkt_data),
    .fwd3_pkt_lat(fwd3_pkt_lat),
    .fwd3_pkt_dp_vld(fwd_pkt_dp_vld[3]),
    .fwd3_pkt_dp_data(fwd3_pkt_dp_data),
    
    // Backpressure
    .pkt_in_bkpr(pkt_in_bkpr)
  );

  // =========================================================================
  // FE Module Instances (4x)
  // =========================================================================
  
  FE u_fe0 (
    .clk(clk),
    .rst_n(rst_n),
    .fwd_pkt_data_vld(fwd_pkt_data_vld[0]),
    .fwd_pkt_data(fwd0_pkt_data),
    .fwd_pkt_lat(fwd0_pkt_lat),
    .fwd_pkt_dp_vld(fwd_pkt_dp_vld[0]),
    .fwd_pkt_dp_data(fwd0_pkt_dp_data),
    .fwded_pkt_data_vld(fwded_pkt_data_vld[0]),
    .fwded_pkt_data(fwded0_pkt_data)
  );
  
  FE u_fe1 (
    .clk(clk),
    .rst_n(rst_n),
    .fwd_pkt_data_vld(fwd_pkt_data_vld[1]),
    .fwd_pkt_data(fwd1_pkt_data),
    .fwd_pkt_lat(fwd1_pkt_lat),
    .fwd_pkt_dp_vld(fwd_pkt_dp_vld[1]),
    .fwd_pkt_dp_data(fwd1_pkt_dp_data),
    .fwded_pkt_data_vld(fwded_pkt_data_vld[1]),
    .fwded_pkt_data(fwded1_pkt_data)
  );
  
  FE u_fe2 (
    .clk(clk),
    .rst_n(rst_n),
    .fwd_pkt_data_vld(fwd_pkt_data_vld[2]),
    .fwd_pkt_data(fwd2_pkt_data),
    .fwd_pkt_lat(fwd2_pkt_lat),
    .fwd_pkt_dp_vld(fwd_pkt_dp_vld[2]),
    .fwd_pkt_dp_data(fwd2_pkt_dp_data),
    .fwded_pkt_data_vld(fwded_pkt_data_vld[2]),
    .fwded_pkt_data(fwded2_pkt_data)
  );
  
  FE u_fe3 (
    .clk(clk),
    .rst_n(rst_n),
    .fwd_pkt_data_vld(fwd_pkt_data_vld[3]),
    .fwd_pkt_data(fwd3_pkt_data),
    .fwd_pkt_lat(fwd3_pkt_lat),
    .fwd_pkt_dp_vld(fwd_pkt_dp_vld[3]),
    .fwd_pkt_dp_data(fwd3_pkt_dp_data),
    .fwded_pkt_data_vld(fwded_pkt_data_vld[3]),
    .fwded_pkt_data(fwded3_pkt_data)
  );

endmodule
